### ISSUE TITLE
freqbasedsim_GTFreq error: Error in GenePop[-1, ] : incorrect number of dimensions

### ISSUE THREAD

**Issue by KealanH** [bwringe/hybriddetective#12]
Hey all having some issues progressing with the example data,

I was able to proceed with the first part fine: 
getTopLoc(GPD = your_example_data_path, panel.size = 50, where.PLINK = your_plink_path, where.PGDspider = your_pgdspider_path)

The file "SimPurePops_50_Loci_Panel.txt" was produced into the right folder and appears fine.
Note: I have also tried your example file "SimPurePops_50_Loci_Panel.txt" file from a previous issue on github and still come up with the following issue.

However when I proceed with the next part:
freqbasedsim_GTFreq(GenePopData = "~/hybriddetective/SimPurePops_50_Loci_Panel.txt", sample.sizePure = 100, sample.sizeF1 = 50, sample.sizeF2 = 10, sample.sizeBC = 10, NumSims = 3, NumReps = 3)

I recieve the error: 
Error in GenePop[-1, ] : incorrect number of dimensions
In addition: Warning message:
In stri_extract_first_regex(string, pattern, opts_regex = opts(pattern)) :
  argument is not an atomic vector; coercing

Any clues as to what I'm doing wrong?

Kind regards, Kealan

**Comment by stevemussmann** [comment]
I'm not the program author, but I ran into this problem today and think I fixed it.

Lines 40 and 41 of freqbasedsim_GTFreq.R read:
```
  GenePop <- as.vector(GenePop)
  GenePop <- GenePop[-1,]
```

I switched the order of these two lines so that the removal of the first record in the input GenePop file occurs before GenePop is converted to a vector. There was a similar problem in freqbasedsim_AlleleSample.R, and I made the same change there as well. 

I don't know why this suddenly became a problem now, given that this R package hasn't been updated in 6 years and I have never encountered this problem previously. Anyways, I forked this repository and applied the fixes. It can be installed with the command ```devtools::install_github("stevemussmann/hybriddetective")```

**Comment by castef** [comment]
Hi, I had the same issue and I could run the analysis with the forked package ("Stevemussmann/hybriddetective"), however I am having issues with the quantification and visualization of the results, both when using the example data or my data: 

nh_multiplotR(NHResults = "mypath/parallelnewhybrids_example/NH.Results/")
and 
nh_plotR(NHResults = "mypath/parallelnewhybrids example/NH.Results/")

Multi-PlotR Progress: 
  |===============================================                                                                                              |  33%Error in names(x) <- value : 
  'names' attribute [7] must be the same length as the vector [6]

and with the command
hybridPowerComp(dir = "mypath/parallelnewhybrids example/NH.Results/")

Error in names(x) <- value : 
  'names' attribute [10] must be the same length as the vector [0]

Anybody with the same issue who could help me please?
Thanks, 
Camilla

**Comment by rystanley** [comment]
I am also trying to figure out why this is an issue. But @stevemussmann  is correct that simple indexing syntax seems to be the error. We will rebuild the package soon to try to fix that issue. In the interim hopefully the forked that Steve made works.

**Comment by rystanley** [comment]
I have started to work through the fix on this indexing bug so will close the issue here. Apologies for the slow reply, I am not the primary owner of the package and so wasn't getting notifications of these issues.
