### ISSUE TITLE
getTopLoc error

### ISSUE THREAD

**Issue by SheaML** [bwringe/hybriddetective#4]
I get the following output and error running getTopLoc. I'm attaching the output "for_FST.txt" file. 

[for_FST.txt](https://github.com/bwringe/hybriddetective/files/1610529/for_FST.txt)

> getTopLoc(GPD ="/mydirs/Mytidy.txt" , panel.size = 100, where.PLINK = your_plink_path, where.PGDspider = your_pgdspider_path)
Reading Data
Creating training and working datasets
Calculating Fst
INFO  20:19:52 - load PGDSpider configuration from: /home/shea/software/PGDSpider_2.1.1.0/spider.conf.xml
Warning: Could not get charToByteConverterClass!
initialize convert process...
read input file...
read input file done.
write output file...
WARN  20:19:54 - FSTAT accepts a maximum of 100 loci!!!
WARN  20:19:55 - The name of a population is missing (no name attribute). It is now recoded as "pop_1"
WARN  20:19:55 - The name of a population is missing (no name attribute). It is now recoded as "pop_2"
write output file done.
Read 4 items
Read 2997 items
Read 56962 items
Error in data.frame(colnames(for.fst)[-1], FSTs) : 
  arguments imply differing number of rows: 2997, 2221

**Comment by SheaML** [comment]
This may be due to an input file that had a large amount of missing data. In this case the "missing" data was erroneously coded as missing during filetype conversion with another R package, so there could be something else malformed about the input file. I'm having no issues with a new file.

**Comment by rspfau** [comment]
What does "WARN 20:19:54 - FSTAT accepts a maximum of 100 loci!!!" mean? Sounds serious if we have more than 100 loci in our dataset.

**Comment by bwringe** [comment]
This is not truly an error. It is a warning from PGDSpider during the conversion from genepop format to FSTAT format, that gets displayed in the terminal as the function runs. This warning is specific to the program FSTAT, which hybriddetective does not use. Hybriddetective uses the R package hierfstat, which does not have a limit on the number of loci.
